name: UpdateFollowers
on: 
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [master]

env:
  INSTA_COOKIE: ${{secrets.INSTA_COOKIE}}
  INSTA_QUERY_HASH: ${{secrets.INSTA_QUERY_HASH}}
  SCRIBD_COOKIE:  ${{secrets.SCRIBD_COOKIE}}

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn package exec:java --file pom.xml
